### PR TITLE
Check space on each iteration

### PR DESCRIPTION
**Pull request by jkaberg**
This way we only delete enough torrents to stay above the threshold, and not all of them who meets the criteria

### CODE REVIEW

**Comment by omaralvarez** [comment]
Yep, this makes sense, although torrent deletion I believe is not synchronous, so we should test this thoroughly to see if the loop is not too fast and space goes down as iterations increase. Anyways, good job, I didn't understand exactly what you meant, I do now.

**Comment by jkaberg** [comment]
@omaralvarez would you mind packaging a new egg and release? :-)

**Comment by omaralvarez** [comment]
I am almost done with all of the milestones, only one more to go. As soon as I finish it, probably in a week or two, I will package and release the 0.5 version.

**Comment by omaralvarez** [comment]
@jkaberg Eggs ready and released: https://github.com/omaralvarez/deluge-autoremoveplus/releases/tag/v0.5

**Comment by jkaberg** [comment]
Thanks @omaralvarez

**Pull request merged**
